name: Publish to Image Registry

on:
  push:
    branches: 
      - master
      
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/veldtech/gotrue/gotrue:${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
