name: Publish to Image Registry

on:
  push:
    branches: 
      - master
      
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/veldtech/gotrue
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag
            type=raw,value=${{ github.run_id }},enable=${{ github.event_name != 'push' }}

      - uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
